version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - source $HOME/.cargo/env
  build:
    commands:
      - cargo build --release
  post_build:
    commands:
      - tar cjf ssmpuller-$(git rev-parse --short HEAD)-$(gcc -dumpmachine).tar.bz2 -C target/release ./ssmpuller

artifacts:
  files:
    - ssmpuller-$(git rev-parse --short HEAD)-$(gcc -dumpmachine).tar.bz2

cache:
  paths:
    - $HOME/.cargo/registry/**/*
